# Task2
### problem as follows:
$$
\max \ \ 19x_1 + 13x_2 + 12x_3 + 17x_4 \\
\begin{align*}
\\
\ & 3x_1 & + & 2x_2 & + & 1x_3 & + & 2x_4 & \leq 225\\
\ & x_1 & + & x_2 & + & x_3 & + & x_4 & \leq 117\\
\ & 4x_1 & + & 3x_2 & + & 3x_3 & + & 4x_4 & \leq 420\\
\end{align*}
$$

In [27]:
import numpy as np
import util as u
from fractions import Fraction

A = np.array([[3,1,4],
             [2,1,3],
             [1,1,1],
             [2,1,4]])
C = np.array([19,13,12,17])
B = np.array([225,117,420])

T = np.concatenate([A.T, np.identity(3)], axis=1)
T = np.column_stack((T, np.zeros(3)))
T = np.column_stack((T, B.T))
T = np.vstack((T, np.concatenate([C, [0,0,0,1,0]])))
u.tableau(T)


|-------+-------+-------+-------+-------+-------+-------+-------+-------+
|    x1 |    x2 |    x3 |    x4 |    x5 |    x6 |    x7 |    -z |     b |
|-------+-------+-------+-------+-------+-------+-------+-------+-------+
|   3.0 |   2.0 |   1.0 |   2.0 |   1.0 |   0.0 |   0.0 |   0.0 | 225.0 |
|   1.0 |   1.0 |   1.0 |   1.0 |   0.0 |   1.0 |   0.0 |   0.0 | 117.0 |
|   4.0 |   3.0 |   1.0 |   4.0 |   0.0 |   0.0 |   1.0 |   0.0 | 420.0 |
|-------+-------+-------+-------+-------+-------+-------+-------+-------+
|  19.0 |  13.0 |  12.0 |  17.0 |   0.0 |   0.0 |   0.0 |   1.0 |   0.0 |
|-------+-------+-------+-------+-------+-------+-------+-------+-------+


$$
\begin{align*}
\ \textit{We can start } & \textit{Revised Simplex by creating:}\\
\ & A_b \\
\ & A_n \\
\ & A_b^{-1}A_n \\
\end{align*}
$$

In [31]:
A_b = T
A_n = T
print(A_b)

[[  3.   2.   1.   2.   1.   0.   0.   0. 225.]
 [  1.   1.   1.   1.   0.   1.   0.   0. 117.]
 [  4.   3.   1.   4.   0.   0.   1.   0. 420.]
 [ 19.  13.  12.  17.   0.   0.   0.   1.   0.]]


# ANWSERS

- 1) 
- 2) 
- 3) at least 2 ( casue in last tableu its reduced cost is -1 so to make it stricty positive at least 2)
- 4) dual variables = shadow price / marginal value = (-1) * (reduced costs of th slacks)
- 5) all slacks are non in basis -> all constraints are tight -> slacks are not needed
- 6) 